# -*- coding: utf-8 -*-
"""Final bigP3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTjY1lLojzmX64vvi9junQPIiBavDH1W
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!pip install mne scikit-learn imbalanced-learn matplotlib seaborn -q

import mne
import numpy as np
import pandas as pd
import glob
import os
import gc

print("Environment ready")

DATA_PATH = "/content/drive/MyDrive/bigP3BCI-data"
SAVE_PATH = "/content/drive/MyDrive/bigP3BCI-data/processed/"
os.makedirs(SAVE_PATH, exist_ok=True)

# --- Auto Run Controller ---
# The script automatically determines what to run next based on
# what has already been saved to Drive. No manual changes needed!
# Just keep hitting Run and it will pick up where it left off.
# Only set RUN_PHASE2 = True manually when ALL files are fully processed.

RUN_PHASE2 = True   # <- SET TO True ONLY when all chunks are fully done
CHUNK_SIZE = 200     # <- How many files to process per run (adjust if needed)

# --- Study Filter ---
# List only the studies you want to process.
# To see all available study folder names, run:
#   import os; print(sorted([d for d in os.listdir(DATA_PATH) if os.path.isdir(os.path.join(DATA_PATH, d))]))
# Folder names must match exactly as they appear in your Google Drive.
# To process ALL studies, set STUDIES = None
STUDIES = ["StudyA", "StudyB", "StudyC", "StudyD", "StudyO"]  # <- UPDATE THIS

all_train_files = [
    f for f in glob.glob(DATA_PATH + "/**/Train/*/*.edf", recursive=True)
    if STUDIES is None or any(f"/{study}/" in f.replace("\\", "/") for study in STUDIES)
]
all_test_files = [
    f for f in glob.glob(DATA_PATH + "/**/Test/*/*.edf", recursive=True)
    if STUDIES is None or any(f"/{study}/" in f.replace("\\", "/") for study in STUDIES)
]

print(f"Studies selected            : {STUDIES if STUDIES else 'ALL'}")
print(f"Total train files available : {len(all_train_files)}")
print(f"Total test files available  : {len(all_test_files)}")

# --- Auto-detect next MODE and CHUNK ---
# Reads the actual chunk numbers from saved filenames to determine exactly
# which chunk and mode to run next. This is robust to partial last chunks
# unlike the old batch-counting approach which got confused by fewer files.

# Extract completed chunk numbers directly from saved filenames
train_chunks_done = set()
for f in glob.glob(SAVE_PATH + "train_epochs_chunk*.npy"):
    chunk_num = int(os.path.basename(f).split("chunk")[1].split("_")[0])
    train_chunks_done.add(chunk_num)

test_chunks_done = set()
for f in glob.glob(SAVE_PATH + "test_epochs_chunk*.npy"):
    chunk_num = int(os.path.basename(f).split("chunk")[1].split("_")[0])
    test_chunks_done.add(chunk_num)

# Build the full list of expected chunk start positions for train and test
all_train_chunk_starts = list(range(0, len(all_train_files), CHUNK_SIZE))
all_test_chunk_starts  = list(range(0, len(all_test_files),  CHUNK_SIZE))

# Find the next missing chunk for train and test
next_train_chunk = next((c for c in all_train_chunk_starts if c not in train_chunks_done), None)
next_test_chunk  = next((c for c in all_test_chunk_starts  if c not in test_chunks_done),  None)

# Logic:
#   If train has a missing chunk -> do train first
#   Else if test has a missing chunk -> do test
#   Else -> all done!
if next_train_chunk is not None:
    MODE        = "train"
    CHUNK_START = next_train_chunk
    CHUNK_END   = min(CHUNK_START + CHUNK_SIZE, len(all_train_files))
elif next_test_chunk is not None:
    MODE        = "test"
    CHUNK_START = next_test_chunk
    CHUNK_END   = min(CHUNK_START + CHUNK_SIZE, len(all_test_files))
else:
    MODE        = "done"
    CHUNK_START = 0
    CHUNK_END   = 0

print(f"Train chunks done : {sorted(train_chunks_done)}")
print(f"Test chunks done  : {sorted(test_chunks_done)}")

if MODE == "done":
    print("\n*** ALL FILES PROCESSED! Set RUN_PHASE2 = True to run Phase 2-6 analysis. ***")
else:
    print(f"Auto-detected: MODE={MODE} | CHUNK_START={CHUNK_START} | CHUNK_END={CHUNK_END}")

# Slice only the files for this session
train_files = all_train_files[CHUNK_START:CHUNK_END]
test_files  = all_test_files[CHUNK_START:CHUNK_END]
print(f"  Files this run: {len(train_files) if MODE == 'train' else len(test_files)}")


# ============================================================
# PHASE 1 - PREPROCESSING
# ============================================================

batch_size = 10
sfreq      = None  # Will be set from the first successfully loaded file
eeg_channels_ref = None  # Will store channel names for ERP plot in Phase 5


# ----------------------------
# TRAIN FILES - Batch Processing
# ----------------------------
# Processes train files only when MODE = "train".
# Instead of loading all files into RAM at once, we process in batches
# of 10, save each batch to Google Drive, then free the memory.
# This keeps RAM usage flat regardless of how many files there are.

if MODE == "done":
    print("\nAll files already processed. Set RUN_PHASE2 = True to run Phase 2-6 analysis.")
elif MODE == "train":
    print("\n--- Running TRAIN preprocessing ---")

    for batch_num, i in enumerate(range(0, len(train_files), batch_size)):
        batch = train_files[i:i + batch_size]
        batch_epochs_list = []
        batch_labels_list = []

        for file in batch:
            # --- Drive Disconnection Guard (Train) ---
            # Google Drive can silently drop its connection during long-running jobs.
            # If read_raw_edf raises OSError (Errno 107), it means Drive disconnected
            # mid-read. We retry up to 3 times, force-remounting Drive each time.
            # If all 3 attempts fail, we skip this file and move on rather than crashing.
            for attempt in range(3):
                try:
                    raw = mne.io.read_raw_edf(file, preload=True, verbose=False)
                    break  # File loaded successfully - exit the retry loop
                except OSError as e:
                    if attempt < 2:
                        print(f"  Warning: Drive disconnected on {os.path.basename(file)}, remounting and retrying... (attempt {attempt+1}/3)")
                        drive.mount('/content/drive', force_remount=True)
                    else:
                        print(f"  Failed to read {os.path.basename(file)} after 3 attempts, skipping.")
                        raw = None
                        break

            if raw is None:
                continue  # Skip this file entirely if all retries failed

            sfreq = raw.info['sfreq']

            # Step 1 - Apply Bandpass Filter
            # Keeps only frequencies where P300 signals exist (0.1-30 Hz)
            raw.filter(0.1, 30, verbose=False)

            # Step 2 - Timepoints of Stimulus
            # Auto threshold adapts to each file's voltage scaling.
            # We find the midpoint between min and max to binarize the signal,
            # then detect rising edges (0->1 transitions) as stimulus onsets.
            stimulus_channel = raw.copy().pick_channels(['StimulusBegin']).get_data()[0]
            threshold = (stimulus_channel.min() + stimulus_channel.max()) / 2
            above = (stimulus_channel > threshold).astype(int)
            event_indices = np.where(np.diff(above) == 1)[0] + 1
            print(f"  [{os.path.basename(file)}] Stimulus events detected: {len(event_indices)}")

            # Step 3 - Type of Stimulus (Target/Non-target)
            # Same auto threshold approach applied to the StimulusType channel
            # to reliably extract binary target (1) vs non-target (0) labels.
            stimulus_type = raw.copy().pick_channels(['StimulusType']).get_data()[0]
            threshold_type = (stimulus_type.min() + stimulus_type.max()) / 2
            labels = (stimulus_type[event_indices] > threshold_type).astype(int)
            print(f"  Target: {np.sum(labels == 1)}, Non-target: {np.sum(labels == 0)}")

            # Step 4 - EEG Channels & Data Extraction
            # Extract all 32 EEG electrode channels and slice 800ms windows
            # starting at each stimulus onset index.
            eeg_channels = [ch for ch in raw.ch_names if ch.startswith("EEG")]
            # Standardize to 16 channels across all studies.
            # Some studies recorded with 16 electrodes, others with 32.
            # We keep only the first 16 to ensure all epochs have matching shapes
            # so batches from different studies can be concatenated without errors.
            eeg_channels = eeg_channels[:16]
            eeg_channels_ref = np.array(eeg_channels)  # Save for ERP plot in Phase 5
            eeg_data = raw.copy().pick_channels(eeg_channels).get_data()
            epoch_length = int(0.8 * sfreq)

            epochs = []
            for idx in event_indices:
                start = idx
                end = idx + epoch_length
                if end <= eeg_data.shape[1]:
                    epochs.append(eeg_data[:, start:end])

            if len(epochs) == 0:
                print(f"  WARNING: No epochs extracted from {file}, skipping.")
                del raw, eeg_data
                gc.collect()
                continue

            epochs = np.array(epochs)

            # Step 5 - Baseline Correction
            # Subtract the mean of the first 100ms from each epoch to remove
            # DC offset and slow drifts, making P300 signals easier to detect.
            baseline_samples = int(0.1 * sfreq)
            baseline = np.mean(epochs[:, :, :baseline_samples], axis=2, keepdims=True)
            epochs = epochs - baseline

            batch_epochs_list.append(epochs)
            batch_labels_list.append(labels[:len(epochs)])  # Align labels to extracted epochs

            # Free per-file memory immediately to keep RAM usage low
            del raw, eeg_data, epochs
            gc.collect()

        if len(batch_epochs_list) == 0:
            print(f"Batch {batch_num} had no valid epochs, skipping save.")
            continue

        # Save batch to Google Drive and free RAM.
        # Filename includes CHUNK_START so batches from different runs
        # are uniquely named and never overwrite each other.
        batch_epochs = np.concatenate(batch_epochs_list)
        batch_labels = np.concatenate(batch_labels_list)
        np.save(SAVE_PATH + f"train_epochs_chunk{CHUNK_START}_batch{batch_num}.npy", batch_epochs)
        np.save(SAVE_PATH + f"train_labels_chunk{CHUNK_START}_batch{batch_num}.npy", batch_labels)
        print(f"Saved: Train chunk {CHUNK_START} batch {batch_num} - shape: {batch_epochs.shape}")

        del batch_epochs, batch_labels, batch_epochs_list, batch_labels_list
        gc.collect()

    # Save channel names for later use in Phase 5 ERP plot
    if eeg_channels_ref is not None:
        np.save(SAVE_PATH + "eeg_channels_ref.npy", eeg_channels_ref)
        np.save(SAVE_PATH + "sfreq_ref.npy", np.array([sfreq]))

    print("\nAll train batches for this chunk processed and saved!")
    print("Next step: rerun with MODE = 'test' and the same CHUNK_START/CHUNK_END.")


# ----------------------------
# TEST FILES - Batch Processing
# ----------------------------
# Processes test files only when MODE = "test".
# Kept separate from train processing so each session stays within
# Free Colab's runtime limits and Drive stays connected throughout.

elif MODE == "test":
    print("\n--- Running TEST preprocessing ---")

    for batch_num, i in enumerate(range(0, len(test_files), batch_size)):
        batch = test_files[i:i + batch_size]
        batch_epochs_list = []
        batch_labels_list = []

        for file in batch:
            # --- Drive Disconnection Guard (Test) ---
            # Same retry logic as the train loop above.
            # Automatically remounts Drive and retries up to 3 times if OSError occurs.
            for attempt in range(3):
                try:
                    raw = mne.io.read_raw_edf(file, preload=True, verbose=False)
                    break  # File loaded successfully - exit the retry loop
                except OSError as e:
                    if attempt < 2:
                        print(f"  Warning: Drive disconnected on {os.path.basename(file)}, remounting and retrying... (attempt {attempt+1}/3)")
                        drive.mount('/content/drive', force_remount=True)
                    else:
                        print(f"  Failed to read {os.path.basename(file)} after 3 attempts, skipping.")
                        raw = None
                        break

            if raw is None:
                continue  # Skip this file entirely if all retries failed

            sfreq = raw.info['sfreq']

            # Step 2 - Timepoints of Stimulus (auto threshold)
            stimulus_channel = raw.copy().pick_channels(['StimulusBegin']).get_data()[0]
            threshold = (stimulus_channel.min() + stimulus_channel.max()) / 2
            above = (stimulus_channel > threshold).astype(int)
            event_indices = np.where(np.diff(above) == 1)[0] + 1
            print(f"  [{os.path.basename(file)}] Stimulus events detected: {len(event_indices)}")

            # Step 3 - Type of Stimulus (Target/Non-target)
            stimulus_type = raw.copy().pick_channels(['StimulusType']).get_data()[0]
            threshold_type = (stimulus_type.min() + stimulus_type.max()) / 2
            labels = (stimulus_type[event_indices] > threshold_type).astype(int)
            print(f"  Target: {np.sum(labels == 1)}, Non-target: {np.sum(labels == 0)}")

            # Step 4 - EEG Channels & Data Extraction
            eeg_channels = [ch for ch in raw.ch_names if ch.startswith("EEG")]
            # Standardize to 16 channels — same as train loop above.
            # Must match train channel count exactly or feature shapes will conflict.
            eeg_channels = eeg_channels[:16]
            eeg_data = raw.copy().pick_channels(eeg_channels).get_data()
            epoch_length = int(0.8 * sfreq)

            epochs = []
            for idx in event_indices:
                start = idx
                end = idx + epoch_length
                if end <= eeg_data.shape[1]:
                    epochs.append(eeg_data[:, start:end])

            if len(epochs) == 0:
                print(f"  WARNING: No epochs extracted from {file}, skipping.")
                del raw, eeg_data
                gc.collect()
                continue

            epochs = np.array(epochs)

            # Step 5 - Baseline Correction
            # For test data, we use each file's own baseline (not the train baseline)
            # to avoid any data leakage from the training set.
            baseline_samples = int(0.1 * sfreq)
            baseline = np.mean(epochs[:, :, :baseline_samples], axis=2, keepdims=True)
            epochs = epochs - baseline

            batch_epochs_list.append(epochs)
            batch_labels_list.append(labels[:len(epochs)])

            del raw, eeg_data, epochs
            gc.collect()

        if len(batch_epochs_list) == 0:
            print(f"Batch {batch_num} had no valid epochs, skipping save.")
            continue

        batch_epochs = np.concatenate(batch_epochs_list)
        batch_labels = np.concatenate(batch_labels_list)
        # Filename includes CHUNK_START so batches from different runs never overwrite each other
        np.save(SAVE_PATH + f"test_epochs_chunk{CHUNK_START}_batch{batch_num}.npy", batch_epochs)
        np.save(SAVE_PATH + f"test_labels_chunk{CHUNK_START}_batch{batch_num}.npy", batch_labels)
        print(f"Saved: Test chunk {CHUNK_START} batch {batch_num} - shape: {batch_epochs.shape}")

        del batch_epochs, batch_labels, batch_epochs_list, batch_labels_list
        gc.collect()

    print("\nAll test batches for this chunk processed and saved!")
    print("Next step: increment CHUNK_START/CHUNK_END and rerun both MODE='train' and MODE='test'.")

elif MODE != 'done':
    raise ValueError(f"Invalid MODE '{MODE}'. Must be 'train' or 'test'.")


# ============================================================
# LOADING + PHASE 2 ONWARDS
# ============================================================
# Only runs when RUN_PHASE2 = True.
# Make sure ALL chunks for BOTH train and test are fully saved to Drive first.
# Tip: Set MODE to either value and RUN_PHASE2 = True to run this section.

if RUN_PHASE2:

    # ----------------------------
    # Load all saved batches back together
    # ----------------------------

    # Remount Drive before loading in case it disconnected during processing
    drive.mount('/content/drive', force_remount=True)
    print("\nLoading all saved batches...")

    # Load EEG channel names and sfreq saved during preprocessing
    eeg_channels_ref = np.load(SAVE_PATH + "eeg_channels_ref.npy")
    sfreq = float(np.load(SAVE_PATH + "sfreq_ref.npy")[0])
    print(f"Loaded sfreq={sfreq}, {len(eeg_channels_ref)} EEG channels")

    # Load all train batches - the chunk* wildcard picks up every chunk from every run
    all_train_epochs, all_train_labels = [], []
    for bf in sorted(glob.glob(SAVE_PATH + "train_epochs_chunk*.npy")):
        lf = bf.replace("epochs", "labels")
        try:
            epochs = np.load(bf)
            labels = np.load(lf)
            all_train_epochs.append(epochs)
            all_train_labels.append(labels)
            print(f"Loaded {os.path.basename(bf)} - shape: {epochs.shape}")
        except Exception as e:
            # A corrupted file means it was saved mid-crash. Delete it from Drive
            # and rerun that chunk to regenerate it.
            print(f"Warning: Skipping corrupted batch {os.path.basename(bf)}: {e}")
            print(f"   -> Delete this file from Drive and rerun its chunk to regenerate it.")

    if len(all_train_epochs) == 0:
        raise RuntimeError("No valid train batches found! Check your SAVE_PATH and rerun Phase 1.")

    train_epochs = np.concatenate(all_train_epochs)
    y_train = np.concatenate(all_train_labels)
    print("train_epochs shape:", train_epochs.shape)
    del all_train_epochs, all_train_labels
    gc.collect()

    # Load all test batches
    all_test_epochs, all_test_labels = [], []
    for bf in sorted(glob.glob(SAVE_PATH + "test_epochs_chunk*.npy")):
        lf = bf.replace("epochs", "labels")
        try:
            epochs = np.load(bf)
            labels = np.load(lf)
            all_test_epochs.append(epochs)
            all_test_labels.append(labels)
            print(f"Loaded {os.path.basename(bf)} - shape: {epochs.shape}")
        except Exception as e:
            print(f"Warning: Skipping corrupted batch {os.path.basename(bf)}: {e}")
            print(f"   -> Delete this file from Drive and rerun its chunk to regenerate it.")

    if len(all_test_epochs) == 0:
        raise RuntimeError("No valid test batches found! Check your SAVE_PATH and rerun Phase 1.")

    test_epochs = np.concatenate(all_test_epochs)
    y_test = np.concatenate(all_test_labels)
    print("test_epochs shape:", test_epochs.shape)
    del all_test_epochs, all_test_labels
    gc.collect()


    # ============================================================
    # PHASE 2 - FEATURE ENGINEERING
    # ============================================================

    # Step 1 - P300 time window (250ms - 500ms)
    # This is the window where the P300 brainwave response typically appears.
    p300_start = int(0.25 * sfreq)
    p300_end   = int(0.5  * sfreq)

    # Step 2 - Extract 96 Features (Mean, Peak, Latency) per epoch
    # Using 3 features per channel x 32 channels = 96 features total.
    # This gives the model richer information than mean amplitude alone.
    mean_feat_train = train_epochs[:, :, p300_start:p300_end].mean(axis=2)    # 32 mean amplitude features
    peak_feat_train = train_epochs[:, :, p300_start:p300_end].max(axis=2)     # 32 peak amplitude features
    lat_feat_train  = train_epochs[:, :, p300_start:p300_end].argmax(axis=2)  # 32 peak latency features
    train_features  = np.concatenate([mean_feat_train, peak_feat_train, lat_feat_train], axis=1)

    mean_feat_test = test_epochs[:, :, p300_start:p300_end].mean(axis=2)
    peak_feat_test = test_epochs[:, :, p300_start:p300_end].max(axis=2)
    lat_feat_test  = test_epochs[:, :, p300_start:p300_end].argmax(axis=2)
    test_features  = np.concatenate([mean_feat_test, peak_feat_test, lat_feat_test], axis=1)

    print("train_features shape:", train_features.shape)
    print("test_features shape:", test_features.shape)

    # Step 3 - Normalize Features
    # StandardScaler makes mean=0 and std=1 for each feature.
    # We fit ONLY on train data so the model never sees test distribution during training.
    from sklearn.preprocessing import StandardScaler

    scaler  = StandardScaler()
    X_train = scaler.fit_transform(train_features)  # Learn mean/std from train, then scale
    X_test  = scaler.transform(test_features)       # Apply the same formula to test

    print("Scaling complete.")
    print("X_train shape:", X_train.shape)
    print("X_test shape:", X_test.shape)


    # ============================================================
    # PHASE 3 - MODEL TRAINING (Baseline Models)
    # ============================================================
    # We train three baseline models to establish a performance benchmark
    # before hyperparameter tuning. All use class_weight='balanced' to
    # compensate for the ~1:6 Target:Non-target imbalance.

    from sklearn.linear_model import LogisticRegression
    from sklearn.svm import SVC
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.metrics import classification_report

    models = {
        "Logistic Regression":    LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42),
        "Support Vector Machine": SVC(class_weight='balanced', probability=True, random_state=42),
        "Random Forest":          RandomForestClassifier(class_weight='balanced', n_estimators=100, random_state=42)
    }

    for name, model in models.items():
        print(f"==================================================")
        print(f"Training {name}...")
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        print(f"Results for {name}:")
        print(classification_report(y_test, y_pred))


    # ============================================================
    # PHASE 4 - HYPERPARAMETER TUNING
    # ============================================================
    # We tune all three models using GridSearchCV.
    # Best model recommendation: SVM with SMOTE + SelectKBest pipeline.
    # Reasoning:
    #   - SVM is the gold standard for P300 BCI in research literature
    #   - SMOTE actively generates synthetic target samples (stronger than class_weight alone)
    #   - SelectKBest filters noisy features, giving SVM a cleaner decision boundary
    #   - LR is fast and interpretable (good for explaining results)
    #   - Random Forest tends to still favour majority class on heavily imbalanced EEG data

    from imblearn.pipeline import Pipeline as ImbPipeline
    from imblearn.over_sampling import SMOTE
    from sklearn.feature_selection import SelectKBest, f_classif
    from sklearn.model_selection import GridSearchCV

    # --- Upgraded SVM Pipeline (Recommended Best Model) ---
    # SMOTE generates synthetic target class samples to further address class imbalance.
    # SelectKBest ranks and keeps only the most informative features.
    # GridSearchCV tests every combination of parameters to find the best settings.
    pipeline_svm = ImbPipeline(steps=[
        ('feature_selection', SelectKBest(score_func=f_classif)),
        ('smote',             SMOTE(random_state=42)),
        ('classifier',        SVC(probability=True, random_state=42))
    ])

    param_grid_svm = {
        'feature_selection__k': [50, 70, 'all'],  # Number of top features to keep
        'classifier__C':        [0.1, 1, 10],     # Penalty strictness
        'classifier__kernel':   ['rbf', 'linear'] # Decision boundary shape
    }

    grid_search_svm = GridSearchCV(
        estimator=pipeline_svm,
        param_grid=param_grid_svm,
        scoring='f1',
        cv=3,
        n_jobs=-1,
        verbose=2
    )

    print("Starting Grid Search for SVM Pipeline...")
    grid_search_svm.fit(X_train, y_train)
    print(f"\nBest SVM Parameters: {grid_search_svm.best_params_}")
    y_pred_svm = grid_search_svm.predict(X_test)
    print("\nResults for Upgraded SVM Pipeline:")
    print(classification_report(y_test, y_pred_svm))


    # --- Upgraded Logistic Regression ---
    # L1 penalty forces unimportant feature weights to exactly 0 (automatic feature selection).
    # L2 penalty just shrinks unimportant weights, keeping all features but reducing their impact.
    # liblinear solver supports both L1 and L2.
    log_reg = LogisticRegression(class_weight='balanced', solver='liblinear', random_state=42, max_iter=2000)

    param_grid_lr = {
        'C':       [0.001, 0.01, 0.1, 1, 10, 100], # Inverse regularization strength
        'penalty': ['l1', 'l2']
    }

    grid_search_lr = GridSearchCV(
        estimator=log_reg,
        param_grid=param_grid_lr,
        scoring='f1',
        cv=5,
        n_jobs=-1,
        verbose=1
    )

    print("Starting Grid Search for Logistic Regression...")
    grid_search_lr.fit(X_train, y_train)
    print(f"\nBest LR Parameters: {grid_search_lr.best_params_}")
    y_pred_lr = grid_search_lr.predict(X_test)
    print("\nResults for Upgraded Logistic Regression:")
    print(classification_report(y_test, y_pred_lr))


    # --- Upgraded Random Forest ---
    # max_depth restricts tree depth to prevent overfitting to the majority class.
    # balanced_subsample recalculates class weights individually for each tree,
    # giving even stronger correction for the class imbalance than 'balanced'.
    rf_model = RandomForestClassifier(random_state=42)

    param_grid_rf = {
        'n_estimators':      [100, 300, 500],
        'max_depth':         [5, 10, 20, None],
        'min_samples_split': [2, 5, 10],
        'class_weight':      ['balanced', 'balanced_subsample']
    }

    grid_search_rf = GridSearchCV(
        estimator=rf_model,
        param_grid=param_grid_rf,
        scoring='f1',
        cv=5,
        n_jobs=-1,
        verbose=1
    )

    print("Starting Grid Search for Random Forest...")
    grid_search_rf.fit(X_train, y_train)
    print(f"\nBest RF Parameters: {grid_search_rf.best_params_}")
    y_pred_rf = grid_search_rf.predict(X_test)
    print("\nResults for Upgraded Random Forest:")
    print(classification_report(y_test, y_pred_rf))


    # ============================================================
    # PHASE 5 - EVALUATION & SCIENTIFIC ANALYSIS
    # ============================================================

    import matplotlib.pyplot as plt
    import seaborn as sns
    from sklearn.metrics import (
        accuracy_score, precision_score, recall_score,
        f1_score, roc_auc_score, confusion_matrix,
        roc_curve, ConfusionMatrixDisplay
    )
    from sklearn.model_selection import permutation_test_score

    # Bundle all tuned models with consistent naming
    # Note: grid_search_svm is the recommended best model
    trained_models = {
        "Logistic Regression": grid_search_lr,
        "SVM":                 grid_search_svm,   # Fixed: was incorrectly named 'grid_search'
        "Random Forest":       grid_search_rf
    }

    # --- Metrics Table ---
    # Summarises Accuracy, Precision, Recall, F1 and AUC for all three models.
    rows = []
    for name, model in trained_models.items():
        y_pred = model.predict(X_test)             # Fixed: variable is X_test, not X_test_scaled
        y_prob = model.predict_proba(X_test)[:, 1]
        rows.append({
            "Model":     name,
            "Accuracy":  round(accuracy_score(y_test, y_pred),   4),
            "Precision": round(precision_score(y_test, y_pred),  4),
            "Recall":    round(recall_score(y_test, y_pred),     4),
            "F1":        round(f1_score(y_test, y_pred),         4),
            "AUC":       round(roc_auc_score(y_test, y_prob),    4)
        })

    metrics_df = pd.DataFrame(rows).set_index("Model")
    print("\n===== METRICS TABLE =====")
    print(metrics_df.to_string())

    # --- Confusion Matrices ---
    # Shows how many targets and non-targets each model correctly/incorrectly classified.
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    for ax, (name, model) in zip(axes, trained_models.items()):
        y_pred = model.predict(X_test)
        cm     = confusion_matrix(y_test, y_pred)
        disp   = ConfusionMatrixDisplay(cm, display_labels=["Non-Target", "Target"])
        disp.plot(ax=ax, colorbar=False, cmap="Blues")
        ax.set_title(name, fontsize=11)
    plt.suptitle("Confusion Matrices", fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig("confusion_matrices.png", dpi=150)
    plt.show()

    # --- ROC Curves ---
    # Plots True Positive Rate vs False Positive Rate for each model.
    # A higher AUC means the model is better at distinguishing target from non-target.
    plt.figure(figsize=(7, 5))
    for name, model in trained_models.items():
        y_prob      = model.predict_proba(X_test)[:, 1]
        fpr, tpr, _ = roc_curve(y_test, y_prob)
        auc         = roc_auc_score(y_test, y_prob)
        plt.plot(fpr, tpr, label=f"{name} (AUC={auc:.3f})")

    plt.plot([0, 1], [0, 1], 'k--', label="Random Baseline")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curves - All Models")
    plt.legend(loc="lower right")
    plt.tight_layout()
    plt.savefig("roc_curves.png", dpi=150)
    plt.show()

    # --- ERP Plot at Pz (Target vs Non-Target) ---
    # Plots the grand average brainwave response at electrode Pz.
    # A clear positive peak around 300ms in the Target class confirms P300 detection.
    # eeg_channels_ref was saved during Phase 1 and loaded at the start of this section.
    pz_idx = np.where(eeg_channels_ref == "EEGPz")[0]
    if len(pz_idx) == 0:                             # Fallback: partial name match
        pz_idx = [i for i, ch in enumerate(eeg_channels_ref) if "Pz" in ch]
    pz_idx = int(pz_idx[0])

    # Grand-average ERP: mean across all epochs of the same class at Pz
    erp_target    = train_epochs[y_train == 1, pz_idx, :].mean(axis=0)
    erp_nontarget = train_epochs[y_train == 0, pz_idx, :].mean(axis=0)
    time_ms       = np.linspace(0, 800, erp_target.shape[0])

    plt.figure(figsize=(9, 4))
    plt.plot(time_ms, erp_target,    label="Target (P300)",  color="blue")
    plt.plot(time_ms, erp_nontarget, label="Non-Target",     color="red", alpha=0.7)
    plt.axvline(x=300, color='gray', linestyle='--', alpha=0.6, label="300 ms mark")
    plt.xlabel("Time (ms)")
    plt.ylabel("Amplitude (uV)")
    plt.title("Grand Average ERP at Pz - Target vs Non-Target")
    plt.legend()
    plt.tight_layout()
    plt.savefig("erp_pz.png", dpi=150)
    plt.show()

    # --- Single vs Multi-Channel Comparison ---
    # Compares a model trained on Pz electrode alone vs all 32 channels.
    # Multi-channel typically wins because spatial brain information adds value.
    s_p3 = int(0.25 * sfreq)
    e_p3 = int(0.50 * sfreq)

    single_train = np.stack([
        train_epochs[:, pz_idx, s_p3:e_p3].mean(axis=1),
        train_epochs[:, pz_idx, s_p3:e_p3].max(axis=1),
        train_epochs[:, pz_idx, s_p3:e_p3].argmax(axis=1)
    ], axis=1)

    single_test = np.stack([
        test_epochs[:, pz_idx, s_p3:e_p3].mean(axis=1),
        test_epochs[:, pz_idx, s_p3:e_p3].max(axis=1),
        test_epochs[:, pz_idx, s_p3:e_p3].argmax(axis=1)
    ], axis=1)

    sc_single   = StandardScaler()
    X_single_tr = sc_single.fit_transform(single_train)
    X_single_te = sc_single.transform(single_test)

    lr_single = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
    lr_single.fit(X_single_tr, y_train)
    y_pred_single = lr_single.predict(X_single_te)

    comp_df = pd.DataFrame({
        "F1":  [f1_score(y_test, y_pred_single),
                metrics_df.loc["Logistic Regression", "F1"]],
        "AUC": [roc_auc_score(y_test, lr_single.predict_proba(X_single_te)[:, 1]),
                metrics_df.loc["Logistic Regression", "AUC"]]
    }, index=["Single Channel (Pz)", "Multi-Channel (32 ch)"])

    print("\n===== SINGLE vs MULTI-CHANNEL =====")
    print(comp_df.round(4).to_string())

    comp_df.plot(kind='bar', figsize=(6, 4), colormap='Set2', edgecolor='black', rot=0)
    plt.title("Single vs Multi-Channel Performance")
    plt.ylabel("Score")
    plt.ylim(0, 1)
    plt.tight_layout()
    plt.savefig("single_vs_multi_channel.png", dpi=150)
    plt.show()

    # Free epoch arrays now that ERP and single-channel analysis are done
    del train_epochs, test_epochs
    gc.collect()


    # ============================================================
    # PHASE 6 - ADVANCED ANALYSIS
    # ============================================================

    from collections import defaultdict

    def load_epochs_from_files(file_list, sfreq_ref):
        """
        Re-reads EDF files, applies bandpass filter, detects stimulus events,
        extracts 800ms epochs and applies baseline correction.
        Returns (epochs array, labels array) or (None, None) if no valid epochs found.
        """
        ep_list, lb_list = [], []
        epoch_len = int(0.8 * sfreq_ref)

        for f in file_list:
            try:
                raw = mne.io.read_raw_edf(f, preload=True, verbose=False)
            except OSError:
                print(f"  Skipping unreadable file: {os.path.basename(f)}")
                continue

            raw.filter(0.1, 30, verbose=False)

            # Detect stimulus onsets using auto threshold
            sc  = raw.copy().pick_channels(['StimulusBegin']).get_data()[0]
            thr = (sc.min() + sc.max()) / 2
            ei  = np.where(np.diff((sc > thr).astype(int)) == 1)[0] + 1

            # Get target/non-target labels using auto threshold
            st  = raw.copy().pick_channels(['StimulusType']).get_data()[0]
            lbs = (st[ei] > (st.min() + st.max()) / 2).astype(int)

            # Extract EEG epochs, keep only those that fit within the recording
            chs  = np.array([ch for ch in raw.ch_names if ch.startswith("EEG")])
            eeg  = raw.copy().pick_channels(chs).get_data()

            valid = (ei + epoch_len) <= eeg.shape[1]
            ei    = ei[valid]
            lbs   = lbs[valid]
            if len(ei) == 0:
                continue

            eps = np.array([eeg[:, i:i + epoch_len] for i in ei])
            bl  = np.mean(eps[:, :, :int(0.1 * sfreq_ref)], axis=2, keepdims=True)
            eps -= bl

            ep_list.append(eps)
            lb_list.append(lbs)

        if not ep_list:
            return None, None
        return np.concatenate(ep_list), np.concatenate(lb_list)


    def epochs_to_features(epochs, sfreq_ref):
        """
        Extracts 96 features (mean, peak, latency x 32 channels)
        from the P300 time window (250-500ms).
        """
        s, e = int(0.25 * sfreq_ref), int(0.50 * sfreq_ref)
        return np.concatenate([
            epochs[:, :, s:e].mean(axis=2),
            epochs[:, :, s:e].max(axis=2),
            epochs[:, :, s:e].argmax(axis=2)
        ], axis=1)


    # --- Cross-Session Evaluation (Leave-One-Session-Out) ---
    # Trains on all sessions except one, tests on the held-out session.
    # This measures how well the model generalises to unseen recording sessions —
    # a critical test for real-world BCI deployment.

    def get_session_id(filepath):
        """Extracts session tag (e.g. SE001) from a file path."""
        for part in filepath.replace("\\", "/").split("/"):
            if part.startswith("SE"):
                return part
        return "UNKNOWN"

    # Group train files by session
    session_files = defaultdict(list)
    for f in all_train_files:
        session_files[get_session_id(f)].append(f)

    session_ids = sorted(session_files.keys())
    print(f"\nSessions found: {session_ids}")

    cross_session_results = []
    for held_out in session_ids:
        train_sess = [f for sid, fl in session_files.items() if sid != held_out for f in fl]
        test_sess  = session_files[held_out]
        if not train_sess or not test_sess:
            continue

        ep_tr, y_tr = load_epochs_from_files(train_sess, sfreq)
        ep_te, y_te = load_epochs_from_files(test_sess,  sfreq)
        if ep_tr is None or ep_te is None:
            continue

        X_tr = epochs_to_features(ep_tr, sfreq)
        X_te = epochs_to_features(ep_te, sfreq)

        sc   = StandardScaler()
        X_tr = sc.fit_transform(X_tr)
        X_te = sc.transform(X_te)

        # Use LR for cross-session as it is fast and generalises well
        lr   = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
        lr.fit(X_tr, y_tr)
        y_pr = lr.predict(X_te)

        cross_session_results.append({
            "Held-Out Session": held_out,
            "Accuracy":         round(accuracy_score(y_te, y_pr),                         4),
            "F1":               round(f1_score(y_te, y_pr),                               4),
            "AUC":              round(roc_auc_score(y_te, lr.predict_proba(X_te)[:, 1]),  4)
        })

    cs_df = pd.DataFrame(cross_session_results).set_index("Held-Out Session")
    print("\n===== CROSS-SESSION EVALUATION (Leave-One-Session-Out) =====")
    print(cs_df.to_string())
    print(f"\nMean F1:  {cs_df['F1'].mean():.4f}  +/-  {cs_df['F1'].std():.4f}")
    print(f"Mean AUC: {cs_df['AUC'].mean():.4f}  +/-  {cs_df['AUC'].std():.4f}")


    # --- RC vs CB Paradigm Comparison ---
    # Compares model performance on Row-Column (RC) vs Checkerboard (CB) stimulus paradigms.
    # This reveals which paradigm produces cleaner P300 signals.
    rc_train = [f for f in all_train_files if "/RC/" in f.replace("\\", "/")]
    cb_train = [f for f in all_train_files if "/CB/" in f.replace("\\", "/")]
    rc_test  = [f for f in all_test_files  if "/RC/" in f.replace("\\", "/")]
    cb_test  = [f for f in all_test_files  if "/CB/" in f.replace("\\", "/")]

    paradigm_results = []
    for paradigm, tr_files, te_files in [("RC (Row-Column)", rc_train, rc_test),
                                          ("CB (Checkerboard)", cb_train, cb_test)]:
        if not tr_files or not te_files:
            print(f"[{paradigm}] No files found - skipping.")
            continue

        ep_tr, y_tr = load_epochs_from_files(tr_files, sfreq)
        ep_te, y_te = load_epochs_from_files(te_files, sfreq)
        if ep_tr is None or ep_te is None:
            continue

        X_tr = epochs_to_features(ep_tr, sfreq)
        X_te = epochs_to_features(ep_te, sfreq)

        sc   = StandardScaler()
        X_tr = sc.fit_transform(X_tr)
        X_te = sc.transform(X_te)

        lr   = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
        lr.fit(X_tr, y_tr)
        y_pr = lr.predict(X_te)

        paradigm_results.append({
            "Paradigm": paradigm,
            "Accuracy": round(accuracy_score(y_te, y_pr),                        4),
            "F1":       round(f1_score(y_te, y_pr),                              4),
            "AUC":      round(roc_auc_score(y_te, lr.predict_proba(X_te)[:, 1]),4)
        })

    para_df = pd.DataFrame(paradigm_results).set_index("Paradigm")
    print("\n===== RC vs CB PARADIGM COMPARISON =====")
    print(para_df.to_string())

    para_df.plot(kind='bar', figsize=(6, 4), colormap='Paired', edgecolor='black', rot=0)
    plt.title("RC vs CB Paradigm Comparison")
    plt.ylabel("Score")
    plt.ylim(0, 1)
    plt.tight_layout()
    plt.savefig("paradigm_comparison.png", dpi=150)
    plt.show()


    # --- Statistical Testing (Permutation Test) ---
    # Shuffles the test labels 100 times to build a null distribution,
    # then checks if the real model score is significantly better than chance.
    # A p-value < 0.05 means the model's performance is statistically significant.
    from sklearn.model_selection import permutation_test_score

    # Identify the best model by AUC from the metrics table
    best_model_name = metrics_df["AUC"].idxmax()
    best_gs         = trained_models[best_model_name]
    best_estimator  = best_gs.best_estimator_  # Unwrap the GridSearchCV to get the actual model

    print(f"\nRunning permutation test on best model: {best_model_name}")

    score, perm_scores, p_value = permutation_test_score(
        best_estimator,
        X_test, y_test,          # Fixed: variable is X_test, not X_test_scaled
        scoring="roc_auc",
        cv=5,                    # 5-fold CV used internally by the test
        n_permutations=100,      # Shuffle labels 100 times to build null distribution
        random_state=42,
        n_jobs=-1
    )

    print(f"\n===== STATISTICAL TESTING - Permutation Test =====")
    print(f"Model:                   {best_model_name}")
    print(f"True AUC:                {score:.4f}")
    print(f"Mean Permuted AUC:       {perm_scores.mean():.4f}  +/-  {perm_scores.std():.4f}")
    print(f"p-value:                 {p_value:.4f}")
    print(f"Significant (p < 0.05)? {'YES' if p_value < 0.05 else 'NO'}")

    plt.figure(figsize=(7, 4))
    plt.hist(perm_scores, bins=20, color='steelblue', edgecolor='black', alpha=0.7, label="Permuted AUC")
    plt.axvline(score, color='red', linewidth=2, label=f"True AUC = {score:.3f}")
    plt.xlabel("AUC Score")
    plt.ylabel("Count")
    plt.title(f"Permutation Test - {best_model_name}")
    plt.legend()
    plt.tight_layout()
    plt.savefig("permutation_test.png", dpi=150)
    plt.show()

else:
    print('\nPhase 2-6 skipped. Set RUN_PHASE2 = True when all chunks are fully processed.')
    print('Run schedule reminder:')
    print('  Step 1: MODE=train, CHUNK_START/END set, RUN_PHASE2=False')
    print('  Step 2: MODE=test,  same CHUNK_START/END, RUN_PHASE2=False')
    print('  Step 3: Repeat Steps 1-2 for each chunk range')
    print('  Step 4: Set RUN_PHASE2=True to run full analysis')